// <auto-generated />
using System;
using Drkb.UniversalBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drkb.UniversalBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260416041426_changed_db")]
    partial class changed_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.MessageStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TypeField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title", "CategoryId")
                        .IsUnique();

                    b.ToTable("MessageStructures");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.SenderUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Messenger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SenderUsers");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.Statistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.Category", b =>
                {
                    b.HasOne("Drkb.UniversalBot.Domain.Entity.Category", "ParentCategory")
                        .WithMany("ChildrenCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.MessageStructure", b =>
                {
                    b.HasOne("Drkb.UniversalBot.Domain.Entity.Category", "Category")
                        .WithMany("StructureOfMessages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.Recommendation", b =>
                {
                    b.HasOne("Drkb.UniversalBot.Domain.Entity.SenderUser", "SenderUser")
                        .WithMany("Recommendations")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.Statistics", b =>
                {
                    b.HasOne("Drkb.UniversalBot.Domain.Entity.Category", "Category")
                        .WithMany("Statistics")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Drkb.UniversalBot.Domain.Entity.SenderUser", "SenderUser")
                        .WithMany("Statistics")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.Category", b =>
                {
                    b.Navigation("ChildrenCategories");

                    b.Navigation("Statistics");

                    b.Navigation("StructureOfMessages");
                });

            modelBuilder.Entity("Drkb.UniversalBot.Domain.Entity.SenderUser", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
